In [1]:
import pickle
import numpy as np

In [2]:
import pandas as pd

In [3]:
with open('train_qa.txt','rb') as f:
    train=pickle.load(f)

In [4]:
train

[(['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.'],
  ['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
  'no'),
 (['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'went',
   'back',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'hallway',
   '.'],
  ['Is', 'Daniel', 'in', 'the', 'bathroom', '?'],
  'no'),
 (['Mary',
   'moved',
   'to',
   'the',
   'bathroom',
   '.',
   'Sandra',
   'journeyed',
   'to',
   'the',
   'bedroom',
   '.',
   'Mary',
   'went',
   'back',
   'to',
   'the',
   'bedroom',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'hallway',
   '.',
   'Sandra',
   'went',
   'to',
   'the',
   'kitchen',
   '.',
   'Daniel',
   'went',
   'back',
   'to',
   'the',
   'bathroom',
   '.'],
  ['Is', 'Daniel', 'in', 'the', '

In [5]:
with open('test_qa.txt','rb') as f:
    test=pickle.load(f)

In [6]:
len(train)

10000

In [7]:
len(test)

1000

In [8]:
train[0][0]

['Mary',
 'moved',
 'to',
 'the',
 'bathroom',
 '.',
 'Sandra',
 'journeyed',
 'to',
 'the',
 'bedroom',
 '.']

In [9]:
all_data=train+test

In [10]:
len(all_data)

11000

In [11]:
vocab=set()
for story,question,answer in all_data:
    vocab=vocab.union(set(story))
    vocab=vocab.union(set(question))

In [12]:
vocab.add('yes')
vocab.add('no')

In [13]:
vocab_len=len(vocab)+1

In [14]:
vocab_len

38

In [15]:
story_len=[len(data[0]) for data in all_data]

In [16]:
max_story_len=max(story_len)

In [17]:
question_len=[len(data[1]) for data in all_data]

In [18]:
max_question_len=max(question_len)

In [19]:
max_question_len

6

In [20]:
import tensorflow as tf

In [21]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [22]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [23]:
tokenizer=Tokenizer(filters=[])

In [24]:
tokenizer.fit_on_texts(vocab)

In [25]:
len(tokenizer.word_index)

37

In [26]:
train_story_text=[]
train_question_text=[]
train_answer_text=[]

In [27]:
for data,question,answer in train:
    train_story_text.append(data)
    train_question_text.append(question)
    train_answer_text.append(answer)

In [28]:
train_question_text

[['Is', 'Sandra', 'in', 'the', 'hallway', '?'],
 ['Is', 'Daniel', 'in', 'the', 'bathroom', '?'],
 ['Is', 'Daniel', 'in', 'the', 'office', '?'],
 ['Is', 'Daniel', 'in', 'the', 'bedroom', '?'],
 ['Is', 'Daniel', 'in', 'the', 'bedroom', '?'],
 ['Is', 'Mary', 'in', 'the', 'bedroom', '?'],
 ['Is', 'Sandra', 'in', 'the', 'office', '?'],
 ['Is', 'Sandra', 'in', 'the', 'bathroom', '?'],
 ['Is', 'Sandra', 'in', 'the', 'bathroom', '?'],
 ['Is', 'Mary', 'in', 'the', 'kitchen', '?'],
 ['Is', 'Sandra', 'in', 'the', 'office', '?'],
 ['Is', 'Mary', 'in', 'the', 'hallway', '?'],
 ['Is', 'Mary', 'in', 'the', 'hallway', '?'],
 ['Is', 'Mary', 'in', 'the', 'hallway', '?'],
 ['Is', 'Mary', 'in', 'the', 'garden', '?'],
 ['Is', 'Sandra', 'in', 'the', 'office', '?'],
 ['Is', 'Sandra', 'in', 'the', 'bathroom', '?'],
 ['Is', 'Sandra', 'in', 'the', 'kitchen', '?'],
 ['Is', 'Mary', 'in', 'the', 'bedroom', '?'],
 ['Is', 'Mary', 'in', 'the', 'kitchen', '?'],
 ['Is', 'Daniel', 'in', 'the', 'bedroom', '?'],
 ['Is', '

In [29]:
train_answer_text

['no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'yes',
 'yes',
 'no',
 'no',
 'yes',
 'yes',
 'no',
 'no',
 'no',
 'yes',
 'no',
 'no',
 'yes',
 'no',
 'yes',
 'no',
 'yes',


In [30]:
train_story_seq=tokenizer.texts_to_sequences(train_story_text)

In [31]:
train_story_seq

[[2, 7, 37, 24, 31, 6, 36, 3, 37, 24, 11, 6],
 [2,
  7,
  37,
  24,
  31,
  6,
  36,
  3,
  37,
  24,
  11,
  6,
  2,
  22,
  12,
  37,
  24,
  11,
  6,
  19,
  22,
  12,
  37,
  24,
  30,
  6],
 [2,
  7,
  37,
  24,
  31,
  6,
  36,
  3,
  37,
  24,
  11,
  6,
  2,
  22,
  12,
  37,
  24,
  11,
  6,
  19,
  22,
  12,
  37,
  24,
  30,
  6,
  36,
  22,
  37,
  24,
  8,
  6,
  19,
  22,
  12,
  37,
  24,
  31,
  6],
 [2,
  7,
  37,
  24,
  31,
  6,
  36,
  3,
  37,
  24,
  11,
  6,
  2,
  22,
  12,
  37,
  24,
  11,
  6,
  19,
  22,
  12,
  37,
  24,
  30,
  6,
  36,
  22,
  37,
  24,
  8,
  6,
  19,
  22,
  12,
  37,
  24,
  31,
  6,
  19,
  28,
  13,
  24,
  20,
  17,
  6,
  19,
  22,
  37,
  24,
  11,
  6],
 [2,
  7,
  37,
  24,
  31,
  6,
  36,
  3,
  37,
  24,
  11,
  6,
  2,
  22,
  12,
  37,
  24,
  11,
  6,
  19,
  22,
  12,
  37,
  24,
  30,
  6,
  36,
  22,
  37,
  24,
  8,
  6,
  19,
  22,
  12,
  37,
  24,
  31,
  6,
  19,
  28,
  13,
  24,
  20,
  17,
  6,
  19,
  22,
  37,

In [32]:
len(train_story_seq)

10000

In [33]:
def vectorize_stories(data,word_index,max_story_len,max_question_len):
    X=[]
    Xq=[]
    Y=[]
    
    for story,question,answer in data:
        x=[word_index[word.lower()] for word in story]
        q=[word_index[word.lower()] for word in question]
        y=np.zeros(len(word_index)+1)
        y[word_index[answer]]=1
        
        X.append(x)
        Xq.append(q)
        Y.append(y)
        
    return(pad_sequences(X,max_story_len),pad_sequences(Xq,max_question_len),np.array(Y))

In [34]:
wordo=tokenizer.word_index
input_train,question_train,answer_train=vectorize_stories(train,wordo,max_story_len,max_question_len)

In [35]:
input_train

array([[ 0,  0,  0, ..., 24, 11,  6],
       [ 0,  0,  0, ..., 24, 30,  6],
       [ 0,  0,  0, ..., 24, 31,  6],
       ...,
       [ 0,  0,  0, ..., 24, 11,  6],
       [ 0,  0,  0, ...,  1, 17,  6],
       [ 0,  0,  0, ...,  5, 17,  6]])

In [36]:
sum(answer_train)

array([   0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0., 4988., 5012.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
          0.,    0.])

In [37]:
len(answer_train)

10000

In [38]:
input_test,question_test,answer_test=vectorize_stories(test,wordo,max_story_len,max_question_len)

In [39]:
sum(answer_test)

array([  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0., 503., 497.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [40]:
import tensorflow.keras as tf

In [41]:
from tensorflow.keras.models import Sequential

In [42]:
from tensorflow.keras.models import Model

In [43]:
from tensorflow.keras.layers import Embedding,Input,Activation,Dense,Permute,dot,add,concatenate,LSTM,Dropout

In [44]:
input_sequence=Input((max_story_len,))

In [45]:
question=Input((max_question_len,))

In [46]:
vocab_size=len(vocab)+1

In [47]:
vocab_size

38

In [48]:
input_encoder_m=Sequential()
input_encoder_m.add(Embedding(input_dim=vocab_size,output_dim=64))
input_encoder_m.add(Dropout(0.3))

In [49]:
input_encoder_c=Sequential()
input_encoder_c.add(Embedding(input_dim=vocab_size,output_dim=max_question_len))
input_encoder_c.add(Dropout(0.3))

In [50]:
question_encoder=Sequential()
question_encoder.add(Embedding(input_dim=vocab_size,output_dim=64,input_length=max_question_len))
question_encoder.add(Dropout(0.3))

In [51]:
question_encoder.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 6, 64)             2432      
_________________________________________________________________
dropout_2 (Dropout)          (None, 6, 64)             0         
Total params: 2,432
Trainable params: 2,432
Non-trainable params: 0
_________________________________________________________________


In [52]:
max_question_len

6

In [53]:
input_encoder_m.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, None, 64)          2432      
_________________________________________________________________
dropout (Dropout)            (None, None, 64)          0         
Total params: 2,432
Trainable params: 2,432
Non-trainable params: 0
_________________________________________________________________


In [54]:
input_encoded_m=input_encoder_m(input_sequence)
input_encoded_c=input_encoder_c(input_sequence)
question_encoded=question_encoder(question)

In [55]:
input_encoded_c

<KerasTensor: shape=(None, 156, 6) dtype=float32 (created by layer 'sequential_1')>

In [56]:
input_encoded_m

<KerasTensor: shape=(None, 156, 64) dtype=float32 (created by layer 'sequential')>

In [57]:
question_encoded

<KerasTensor: shape=(None, 6, 64) dtype=float32 (created by layer 'sequential_2')>

In [58]:
match=dot([input_encoded_m,question_encoded],axes=(2,2))

In [59]:
match=Activation('softmax')(match)

In [60]:
response=add([match,input_encoded_c])

In [61]:
response.shape

TensorShape([None, 156, 6])

In [62]:
response=Permute((2,1))(response)

In [63]:
response.shape

TensorShape([None, 6, 156])

In [64]:
answer=concatenate([response,question_encoded])

In [65]:
answer.shape

TensorShape([None, 6, 220])

In [66]:
answer=LSTM(32)(answer)

In [67]:
answer=Dropout(0.5)(answer)

In [68]:
answer=Dense(vocab_size)(answer)

In [69]:
answer=Activation('softmax')(answer)

In [70]:
model=Model([input_sequence,question],answer)

In [71]:
model.compile(optimizer='rmsprop',loss='categorical_crossentropy',metrics=['accuracy'])

In [72]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            [(None, 156)]        0                                            
__________________________________________________________________________________________________
input_2 (InputLayer)            [(None, 6)]          0                                            
__________________________________________________________________________________________________
sequential (Sequential)         (None, None, 64)     2432        input_1[0][0]                    
__________________________________________________________________________________________________
sequential_2 (Sequential)       (None, 6, 64)        2432        input_2[0][0]                    
______________________________________________________________________________________________

In [73]:
history=model.fit([input_train,question_train],answer_train,batch_size=32,epochs=100,validation_data=([input_test,question_test],answer_test))

Epoch 1/100
313/313 [==============================] - 5s 9ms/step - loss: 1.2485 - accuracy: 0.4981 - val_loss: 0.7026 - val_accuracy: 0.4970
Epoch 2/100
313/313 [==============================] - 2s 6ms/step - loss: 0.7184 - accuracy: 0.4845 - val_loss: 0.6945 - val_accuracy: 0.4970
Epoch 3/100
313/313 [==============================] - 2s 6ms/step - loss: 0.6973 - accuracy: 0.5006 - val_loss: 0.6933 - val_accuracy: 0.4970
Epoch 4/100
313/313 [==============================] - 2s 6ms/step - loss: 0.6953 - accuracy: 0.5003 - val_loss: 0.6936 - val_accuracy: 0.5030
Epoch 5/100
313/313 [==============================] - 2s 6ms/step - loss: 0.6952 - accuracy: 0.5001 - val_loss: 0.6935 - val_accuracy: 0.5030
Epoch 6/100
313/313 [==============================] - 2s 6ms/step - loss: 0.6950 - accuracy: 0.5003 - val_loss: 0.6941 - val_accuracy: 0.4970
Epoch 7/100
313/313 [==============================] - 2s 6ms/step - loss: 0.6953 - accuracy: 0.4944 - val_loss: 0.6936 - val_accuracy: 0.4970

Epoch 58/100
313/313 [==============================] - 2s 6ms/step - loss: 0.2695 - accuracy: 0.8846 - val_loss: 0.3696 - val_accuracy: 0.8360
Epoch 59/100
313/313 [==============================] - 2s 6ms/step - loss: 0.2647 - accuracy: 0.8841 - val_loss: 0.3739 - val_accuracy: 0.8310
Epoch 60/100
313/313 [==============================] - 2s 6ms/step - loss: 0.2701 - accuracy: 0.8775 - val_loss: 0.3981 - val_accuracy: 0.8350
Epoch 61/100
313/313 [==============================] - 2s 6ms/step - loss: 0.2610 - accuracy: 0.8853 - val_loss: 0.3736 - val_accuracy: 0.8320
Epoch 62/100
313/313 [==============================] - 2s 6ms/step - loss: 0.2743 - accuracy: 0.8808 - val_loss: 0.3664 - val_accuracy: 0.8270
Epoch 63/100
313/313 [==============================] - 2s 6ms/step - loss: 0.2559 - accuracy: 0.8859 - val_loss: 0.3594 - val_accuracy: 0.8340
Epoch 64/100
313/313 [==============================] - 2s 6ms/step - loss: 0.2587 - accuracy: 0.8841 - val_loss: 0.3631 - val_accuracy:

In [74]:
pred_results=model.predict([input_test,question_test])

In [78]:
val_max=np.argmax(pred_results[0])

In [82]:
for key,val in tokenizer.word_index.items():
    if val==val_max:
        print(key)

no


In [83]:
pred_results[0][val_max]

0.99999523

In [237]:
my_story="Sandra is in the office . John took the football there"

In [238]:
questiono="Is the football in the office ?"

In [239]:
questiono.split()

['Is', 'the', 'football', 'in', 'the', 'office', '?']

In [240]:
my_data=[(my_story.split(),questiono.split(),'yes')]

In [241]:
my_data

[(['Sandra',
   'is',
   'in',
   'the',
   'office',
   '.',
   'John',
   'took',
   'the',
   'football',
   'there'],
  ['Is', 'the', 'football', 'in', 'the', 'office', '?'],
  'yes')]

In [242]:
my_stor,my_ques,my_ans=vectorize_stories(my_data,tokenizer.word_index,max_story_len,max_question_len)

In [243]:
my_ans

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.]])

In [244]:
predo=model.predict([my_stor,my_ques])

In [245]:
my_ques

array([[24, 20,  9, 24, 35, 23]])

In [246]:
for key,val in tokenizer.word_index.items():
    if val==predo.argmax():
        print(key)

yes


In [247]:
np.argmax(predo[0])

15

In [248]:
tokenizer.word_index['yes']

15

In [249]:
tokenizer.word_index['no']

14

In [250]:
pred_results[0][15]

4.7390668e-06

In [166]:
tokenizer.word_index

{'milk': 1,
 'mary': 2,
 'journeyed': 3,
 'grabbed': 4,
 'apple': 5,
 '.': 6,
 'moved': 7,
 'kitchen': 8,
 'in': 9,
 'down': 10,
 'bedroom': 11,
 'back': 12,
 'up': 13,
 'no': 14,
 'yes': 15,
 'dropped': 16,
 'there': 17,
 'put': 18,
 'daniel': 19,
 'football': 20,
 'took': 21,
 'went': 22,
 '?': 23,
 'the': 24,
 'discarded': 25,
 'got': 26,
 'is': 27,
 'picked': 28,
 'john': 29,
 'hallway': 30,
 'bathroom': 31,
 'left': 32,
 'garden': 33,
 'travelled': 34,
 'office': 35,
 'sandra': 36,
 'to': 37}